# Generated by Django 5.0 on 2024-02-21 13:39

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, editable=False, max_length=200),
        ),
    ]
