# Generated by Django 5.0 on 2024-02-25 10:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_alter_salary_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(28.0339, 1.6596), srid=4326),
        ),
    ]
