# Generated by Django 5.0 on 2024-02-25 10:24

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0003_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(3.0589, 36.7539), srid=4326),
        ),
    ]
