# Generated by Django 5.0 on 2024-02-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0004_alter_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_expense',
            name='barcode',
        ),
    ]
