# Generated by Django 5.0 on 2024-03-11 11:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0006_alter_absence_date_alter_advance_on_salary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ', unique=True),
        ),
    ]
