# Generated by Django 5.0 on 2024-03-14 20:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0007_alter_employee_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phonenumber2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='DZ'),
        ),
    ]
