# Generated by Django 5.0 on 2024-05-14 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0011_alter_employee_phonenumber2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phonenumber2',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{7}$')]),
        ),
    ]
