# Generated by Django 5.0 on 2024-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
