# Generated by Django 5.0 on 2024-01-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField()),
                ('purchasing_price', models.FloatField()),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('limit_less', models.IntegerField()),
                ('limit_more', models.IntegerField()),
                ('num_per_item', models.IntegerField(blank=True, default=0)),
                ('item_per_carton', models.IntegerField(blank=True, default=0)),
                ('sale_price', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(blank=True, default=' ', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.category')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='Clients_and_Products.Cart_Products', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='cart_products',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='Clients_and_Products.Order_Product', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
    ]
