# Generated by Django 5.0 on 2024-02-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='images/category.webp', null=True, upload_to='images/product_types')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/category.webp', null=True, upload_to='images/categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.producttype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
