# Generated by Django 5.0 on 2024-02-08 08:12

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0002_alter_cart_products_quantity'),
    ]

    operations = [

    ]
