# Generated by Django 5.0 on 2024-01-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0003_client_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
