# Generated by Django 5.0 on 2024-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0004_alter_client_id_alter_client_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/category.webp', null=True, upload_to='images/products'),
        ),
    ]
