# Generated by Django 5.0 on 2024-01-11 16:27

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0004_product_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='expire_date',
            field=models.DateField(default=base.models.get_expiration_date),
        ),
    ]
