# Generated by Django 5.0 on 2024-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0005_order_total_points_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='total_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
