# Generated by Django 5.0 on 2024-01-14 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0005_alter_points_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='debts',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
