# Generated by Django 5.0 on 2024-02-09 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0006_order_product_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200),
        ),
    ]
