# Generated by Django 5.0 on 2024-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0007_order_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barcode',
            field=models.CharField(max_length=200),
        ),
    ]
