# Generated by Django 5.0 on 2024-02-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0008_remove_message_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to='Clients_and_Products.client'),
            preserve_default=False,
        ),
    ]
