# Generated by Django 4.2.10 on 2024-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0010_alter_cart_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_product',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
