# Generated by Django 4.2.10 on 2024-02-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0011_order_barcode_order_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='total_points',
            field=models.IntegerField(),
        ),
    ]
