# Generated by Django 5.0 on 2024-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0012_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
