# Generated by Django 4.2.10 on 2024-02-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0013_cart_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adeversting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/adversting')),
            ],
        ),
    ]
