# Generated by Django 4.2.10 on 2024-02-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0014_adeversting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adeversting',
            new_name='Advertising',
        ),
    ]
