# Generated by Django 5.0 on 2024-02-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0015_order_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
