# Generated by Django 5.0 on 2024-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0016_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
