# Generated by Django 5.0 on 2024-02-17 09:36

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0018_remove_order_products_num_remove_order_total_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, max_length=200),
        ),
    ]
