# Generated by Django 5.0 on 2024-02-17 10:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0019_alter_cart_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default=base.models.generate_barcode, max_length=200),
        ),
    ]
