# Generated by Django 5.0 on 2024-02-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0020_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='store_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
