# Generated by Django 5.0 on 2024-02-25 08:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0021_client_store_name_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phonenumber2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='DZ'),
        ),
    ]
