# Generated by Django 5.0 on 2024-03-02 17:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0025_alter_client_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(10, 20), null=True, srid=4326),
        ),
    ]
