# Generated by Django 5.0 on 2024-03-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0027_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id']},
        ),
    ]
