# Generated by Django 5.0 on 2024-03-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0034_alter_client_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
