# Generated by Django 5.0 on 2024-05-15 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0038_alter_client_phonenumber2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonenumber',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{8}$')]),
        ),
    ]
