# Generated by Django 5.0 on 2024-06-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0040_alter_client_phonenumber2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
