# Generated by Django 5.0 on 2024-02-06 13:53

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Human_Resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.IntegerField()),
                ('total_price', models.FloatField()),
            ],
            options={
                'ordering': ['-product_id'],
            },
        ),
        migrations.CreateModel(
            name='ManualReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(default='000 208 0660', max_length=20)),
                ('recive_payment', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('reclaimed_products', models.FloatField(blank=True, default=0.0, null=True)),
                ('previous_depts', models.FloatField(blank=True, default=0.0, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ManualReceipt_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('num_item', models.IntegerField()),
                ('total_price', models.FloatField(default=0)),
                ('product_points', models.IntegerField()),
            ],
            options={
                'ordering': ['-product_id'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(default='000 208 0660', max_length=20)),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0.0)),
                ('Reclaimed_products', models.FloatField(blank=True, default=0.0)),
                ('previous_depts', models.FloatField(blank=True, default=0.0)),
                ('remaining_amount', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Output_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('product_points', models.IntegerField()),
            ],
            options={
                'ordering': ['-product_id'],
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(default='000 208 0660', max_length=20)),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Reclaimed_products', models.FloatField(blank=True, default=0.0, null=True)),
                ('previous_depts', models.FloatField(blank=True, default=0.0, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
