# Generated by Django 5.0 on 2024-01-10 09:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients_and_Products', '0001_initial'),
        ('Human_Resources', '0001_initial'),
        ('base', '0034_alter_output_verify_code_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_verefy', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(default='000 208 0660', max_length=20)),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Reclaimed_products', models.FloatField(blank=True, default=0.0, null=True)),
                ('previous_depts', models.FloatField(blank=True, default=0.0, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Incoming_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.incoming')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'ordering': ['-product_id'],
            },
        ),
        migrations.AddField(
            model_name='incoming',
            name='products',
            field=models.ManyToManyField(through='Receipts.Incoming_Product', to='base.product'),
        ),
        migrations.CreateModel(
            name='ManualReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField(blank=True, null=True)),
                ('phonenumber', models.CharField(default='000 208 0660', max_length=20)),
                ('recive_payment', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('reclaimed_products', models.FloatField(blank=True, default=0.0, null=True)),
                ('previous_depts', models.FloatField(blank=True, default=0.0, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ManualReceipt_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('num_item', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('manualreceipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.manualreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'ordering': ['-product_id'],
            },
        ),
        migrations.AddField(
            model_name='manualreceipt',
            name='products',
            field=models.ManyToManyField(through='Receipts.ManualReceipt_Products', to='base.product'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField(blank=True, default=0, null=True)),
                ('phonenumber', models.CharField(default='000 208 0660', max_length=20)),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Reclaimed_products', models.FloatField(blank=True, default=0.0, null=True)),
                ('previous_depts', models.FloatField(blank=True, default=0.0, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('delivered', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Output_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.output')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'ordering': ['-products_id'],
            },
        ),
        migrations.AddField(
            model_name='output',
            name='products',
            field=models.ManyToManyField(through='Receipts.Output_Products', to='base.product'),
        ),
    ]
