# Generated by Django 5.0 on 2024-01-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0002_product_alter_cart_items_and_more'),
        ('Receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='products',
            field=models.ManyToManyField(through='Receipts.Incoming_Product', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='incoming_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='manualreceipt',
            name='products',
            field=models.ManyToManyField(through='Receipts.ManualReceipt_Products', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='manualreceipt_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='output',
            name='products',
            field=models.ManyToManyField(through='Receipts.Output_Products', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='output_products',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
    ]
