# Generated by Django 5.0 on 2024-02-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='phonenumber',
            new_name='client_service',
        ),
        migrations.RenameField(
            model_name='manualreceipt',
            old_name='phonenumber',
            new_name='client_service',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='phonenumber',
            new_name='client_service',
        ),
    ]
