# Generated by Django 5.0 on 2024-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='Reclaimed_products',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='output',
            name='discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='output',
            name='previous_depts',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='output',
            name='remaining_amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='output',
            name='verify_code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
