# Generated by Django 4.2.10 on 2024-02-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('Receipts', '0003_alter_incoming_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='base.day'),
        ),
    ]
