# Generated by Django 5.0 on 2024-01-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0003_alter_output_reclaimed_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='code_verefy',
        ),
        migrations.RemoveField(
            model_name='manualreceipt',
            name='verify_code',
        ),
        migrations.RemoveField(
            model_name='output',
            name='verify_code',
        ),
    ]
