# Generated by Django 5.0 on 2024-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0003_rename_phonenumber_incoming_client_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreceipt',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
