# Generated by Django 5.0 on 2024-02-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0004_manualreceipt_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
