# Generated by Django 5.0 on 2024-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0004_remove_incoming_code_verefy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreceipt_products',
            name='product_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
