# Generated by Django 5.0 on 2024-01-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0005_manualreceipt_products_product_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='output_products',
            name='product_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
