# Generated by Django 5.0 on 2024-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0005_incoming_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
