# Generated by Django 5.0 on 2024-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0006_output_products_product_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt_products',
            name='num_item',
            field=models.IntegerField(),
        ),
    ]
