# Generated by Django 5.0 on 2024-02-17 09:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0006_output_freeze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, editable=False, max_length=200),
        ),
    ]
