# Generated by Django 5.0 on 2024-01-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0007_alter_manualreceipt_products_num_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='output_products',
            options={'ordering': ['-product_id']},
        ),
        migrations.RenameField(
            model_name='output',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='output_products',
            old_name='products',
            new_name='product',
        ),
    ]
