# Generated by Django 5.0 on 2024-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0008_alter_manualreceipt_barcode_alter_output_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreceipt',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
