# Generated by Django 4.2.10 on 2024-02-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0008_alter_manualreceipt_barcode_alter_output_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenManualReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.incoming')),
            ],
        ),
    ]
