# Generated by Django 5.0 on 2024-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0009_manualreceipt_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt',
            name='serial',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
