# Generated by Django 4.2.10 on 2024-02-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0009_frozenmanualreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenmanualreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.manualreceipt'),
        ),
    ]
