# Generated by Django 5.0 on 2024-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0010_alter_manualreceipt_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='serial',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='serial',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
