# Generated by Django 5.0 on 2024-02-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0011_incoming_serial_output_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenIncomingReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.incoming')),
            ],
        ),
        migrations.CreateModel(
            name='FrozenManualReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.manualreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='FrozenOutputReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.output')),
            ],
        ),
    ]
