# Generated by Django 5.0 on 2024-02-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0012_frozenincomingreceipts_frozenmanualreceipts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrozenOutputReceipts',
            new_name='FrozenIncomingReceipt',
        ),
        migrations.RenameModel(
            old_name='FrozenManualReceipts',
            new_name='FrozenManualReceipt',
        ),
        migrations.RenameModel(
            old_name='FrozenIncomingReceipts',
            new_name='FrozenOutputReceipt',
        ),
        migrations.AlterField(
            model_name='frozenincomingreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.incoming'),
        ),
        migrations.AlterField(
            model_name='frozenoutputreceipt',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.output'),
        ),
    ]
