# Generated by Django 5.0 on 2024-02-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0013_rename_frozenoutputreceipts_frozenincomingreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreceipt',
            name='adjustment_applied',
            field=models.BooleanField(default=False),
        ),
    ]
