# Generated by Django 5.0 on 2024-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0014_manualreceipt_adjustment_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='adjustment_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='output',
            name='adjustment_applied',
            field=models.BooleanField(default=False),
        ),
    ]
