# Generated by Django 5.0 on 2024-03-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0018_manualreceipt_shipping_cost_output_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualreceipt',
            name='shipping_cost',
        ),
    ]
