# Generated by Django 5.0 on 2024-04-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0019_remove_manualreceipt_shipping_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualreceipt_products',
            old_name='price',
            new_name='sale_price',
        ),
    ]
