# Generated by Django 5.0 on 2024-04-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0020_rename_price_manualreceipt_products_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt',
            name='remaining_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
