# Generated by Django 5.0 on 2024-09-11 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0041_alter_order_options'),
        ('Receipts', '0021_alter_manualreceipt_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='products',
        ),
        migrations.RemoveField(
            model_name='incoming_product',
            name='product',
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='barcode',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='image',
            field=models.ImageField(blank=True, default='images/account.jpg', null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='item_per_carton',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='limit_less',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='limit_more',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='made_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='name',
            field=models.CharField(default='cola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='num_per_item',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='purchasing_price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incoming_product',
            name='sale_price',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
    ]
