# Generated by Django 5.0 on 2024-09-11 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0041_alter_order_options'),
        ('Receipts', '0022_remove_incoming_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualreceipt',
            name='products',
        ),
        migrations.RemoveField(
            model_name='manualreceipt_products',
            name='product',
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='barcode',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='image',
            field=models.ImageField(blank=True, default='images/account.jpg', null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='item_per_carton',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='limit_less',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='limit_more',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='made_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='name',
            field=models.CharField(default='cola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='num_per_item',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='purchasing_price',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualreceipt_products',
            name='quantity',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manualreceipt_products',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
