# Generated by Django 4.2.8 on 2024-01-11 00:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0080_remove_incoming_employee_remove_incoming_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_verefy', models.IntegerField(blank=True, null=True)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('recive_pyement', models.FloatField(blank=True, default=0)),
                ('discount', models.FloatField(blank=True, default=0)),
                ('Reclaimed_products', models.FloatField(blank=True, default=0)),
                ('previous_depts', models.FloatField(blank=True, default=True)),
                ('remaining_amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('recive_payment', models.FloatField()),
                ('reclaimed_products', models.FloatField()),
                ('previous_depts', models.FloatField()),
                ('remaining_amount', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReceipt_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('num_item', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('manualreceipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.manualreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='manualreceipt',
            name='products',
            field=models.ManyToManyField(through='Inventory.ManualReceipt_Products', to='base.product'),
        ),
        migrations.CreateModel(
            name='Incoming_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.incoming')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='incoming',
            name='products',
            field=models.ManyToManyField(through='Inventory.Incoming_Product', to='base.product'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier'),
        ),
    ]
