# Generated by Django 5.0 on 2024-01-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients_and_Products', '0001_initial'),
        ('Human_Resources', '0001_initial'),
        ('base', '0034_alter_output_verify_code_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default=' ', max_length=100, null=True)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('receipt_num', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Debt_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(blank=True, default='_', max_length=60, null=True)),
                ('receipt_num', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client')),
            ],
        ),
        migrations.CreateModel(
            name='Debt_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(blank=True, default='_', max_length=60, null=True)),
                ('check_num', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite_name', models.CharField(max_length=50)),
                ('detail_deposite', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('total', models.FloatField()),
                ('verify_code', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(blank=True, default='_', max_length=60, null=True)),
                ('receipt_num', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Recieved_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(blank=True, default='_', max_length=60, null=True)),
                ('receipt_num', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_name', models.CharField(max_length=50)),
                ('details_withdraw', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('total', models.FloatField()),
                ('verify_code', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client')),
            ],
        ),
    ]
