# Generated by Django 4.2.10 on 2024-02-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients_and_Products', '0001_initial'),
        ('base', '0001_initial'),
        ('Company_Fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt_supplier',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier'),
        ),
        migrations.AddField(
            model_name='debt_client',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client'),
        ),
    ]
