# Generated by Django 5.0 on 2024-01-11 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_client',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
