# Generated by Django 5.0 on 2024-01-11 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0003_alter_debt_client_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_supplier',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
