# Generated by Django 4.2.10 on 2024-02-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_alter_salary_barcode'),
        ('Company_Fund', '0003_registry_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee'),
        ),
    ]
