# Generated by Django 5.0 on 2024-02-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0004_withdraw_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='registry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Fund.registry'),
        ),
    ]
