# Generated by Django 5.0 on 2024-02-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0006_expense_added_to_registry_payment_added_to_registry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt_client',
            name='added_to_registry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debt_supplier',
            name='added_to_registry',
            field=models.BooleanField(default=True),
        ),
    ]
