# Generated by Django 5.0 on 2024-02-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0007_debt_client_added_to_registry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_client',
            name='added_to_registry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debt_supplier',
            name='added_to_registry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_to_registry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='added_to_registry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recieved_payment',
            name='added_to_registry',
            field=models.BooleanField(default=False),
        ),
    ]
