# Generated by Django 5.0 on 2024-02-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0008_alter_debt_client_added_to_registry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt_supplier',
            old_name='check_num',
            new_name='receipt_num',
        ),
    ]
