# Generated by Django 5.0 on 2024-02-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0009_rename_check_num_debt_supplier_receipt_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
