# Generated by Django 5.0 on 2024-02-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Fund', '0010_alter_expense_receipt_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_client',
            name='receipt_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='debt_supplier',
            name='receipt_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recieved_payment',
            name='receipt_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
