# Generated by Django 5.0 on 2023-12-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming_products',
            old_name='num_item',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='incoming_products',
            name='purch_price',
        ),
    ]
