# Generated by Django 5.0 on 2024-01-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='http://85.31.237.33/static/images/Danac.jpg', null=True, upload_to='images/users'),
        ),
    ]
