# Generated by Django 5.0 on 2023-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_order_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='limit',
            new_name='item_per_carton',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='info',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='product',
            name='limit_less',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='limit_more',
            field=models.IntegerField(default=0),
        ),
    ]
