# Generated by Django 5.0 on 2023-12-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_debt_client_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DamagedProduct',
        ),
    ]
