# Generated by Django 5.0 on 2024-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_options_supplier_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='info',
            field=models.TextField(default='_', max_length=500),
        ),
    ]
