# Generated by Django 5.0 on 2023-12-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_num_item_incoming_products_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='incoming',
            name='agent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='code_verefy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='num_truck',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='previous_depts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='recive_pyement',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.supplier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.usertype'),
        ),
    ]
