# Generated by Django 5.0 on 2023-12-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verivecation',
            new_name='is_verified',
        ),
    ]
