# Generated by Django 5.0 on 2023-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usertype_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
