# Generated by Django 5.0 on 2023-12-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employee_paercentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='paercentage',
            new_name='percentage',
        ),
    ]
