# Generated by Django 5.0 on 2024-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_supplier_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='info',
            field=models.TextField(blank=True, default='_', max_length=500),
        ),
    ]
