# Generated by Django 5.0 on 2023-12-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_limit_product_item_per_carton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('receipt_num', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debt_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(max_length=50)),
                ('check_num', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_deposite', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('verify_code', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('receipt_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.FloatField(default=0)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='WithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_withdraw', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('verify_code', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
