# Generated by Django 5.0 on 2023-12-16 20:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_usertype_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_expence', models.CharField(max_length=50)),
                ('name_user', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('num_reciept', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_withdraw', models.CharField(max_length=50)),
                ('name_user', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('verify_code', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Expense',
            new_name='ExtraExpense',
        ),
        migrations.RemoveField(
            model_name='incoming_products',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='incoming_products',
            name='products',
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_deposite', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('verify_code', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='DeptsClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_pyement', models.FloatField()),
                ('pyement_method', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='DeptsSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recive_pyement', models.FloatField()),
                ('pyement_method', models.CharField(max_length=10)),
                ('name_bank', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('recive_pyement', models.FloatField()),
                ('Reclaimed_products', models.FloatField()),
                ('previous_debts', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReciept_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('manualreciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.manualreciept')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='manualreciept',
            name='products',
            field=models.ManyToManyField(through='base.ManualReciept_Products', to='base.product'),
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
        migrations.DeleteModel(
            name='Incoming_Products',
        ),
    ]
