# Generated by Django 5.0 on 2023-12-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_paercentage_employee_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='percentage',
        ),
    ]
