# Generated by Django 5.0 on 2024-01-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_incoming_reclaimed_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sale_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='truck_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output_products',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
