# Generated by Django 5.0 on 2023-12-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
