# Generated by Django 5.0 on 2023-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_debt_client_debt_supplier_deposite_expense_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_client',
            name='amount',
            field=models.FloatField(),
        ),
    ]
