# Generated by Django 5.0 on 2023-12-20 05:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_damagedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_on_salary',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt_supplier',
            name='bank_name',
            field=models.CharField(default='_', max_length=60),
        ),
    ]
