# Generated by Django 5.0 on 2023-12-13 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 2, 58, 7, 61099, tzinfo=datetime.timezone.utc)),
        ),
    ]
