# Generated by Django 5.0 on 2023-12-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_employee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='barcode',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
