# Generated by Django 5.0 on 2024-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_employee_sale_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(),
        ),
    ]
