# Generated by Django 5.0 on 2023-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_debt_client_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_supplier',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
    ]
