# Generated by Django 5.0 on 2023-12-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_advance_on_salary_date_alter_debt_supplier_bank_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
