# Generated by Django 5.0 on 2023-12-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_debt_supplier_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='products',
        ),
        migrations.CreateModel(
            name='Medium_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medium')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='medium',
            name='products',
            field=models.ManyToManyField(through='base.Medium_Products', to='base.product'),
        ),
    ]
