# Generated by Django 5.0 on 2023-12-20 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('percentage', models.FloatField()),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
                ('overtime', models.FloatField(default=0.0)),
                ('absence', models.FloatField(default=0.0)),
                ('bonus', models.FloatField(default=0.0)),
                ('discout', models.FloatField(default=0.0)),
                ('advances', models.FloatField(default=0.0)),
                ('extra_expense', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='base.employee')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_employee_salaries', to='base.employee')),
            ],
        ),
    ]
