# Generated by Django 5.0 on 2023-12-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
