# Generated by Django 5.0 on 2023-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_salary_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='absence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salary',
            name='advances',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salary',
            name='discout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salary',
            name='extra_expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salary',
            name='overtime',
            field=models.FloatField(default=0.0),
        ),
    ]
