# Generated by Django 5.0 on 2023-12-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_options_product_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
