# Generated by Django 4.2.10 on 2024-02-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_supplier_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='f', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_store',
            field=models.CharField(default='f', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='f', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_hours',
            field=models.CharField(default='f', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='town',
            field=models.CharField(default='f', max_length=50),
        ),
    ]
