# Generated by Django 5.0 on 2023-12-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-added']},
        ),
    ]
