# Generated by Django 5.0 on 2023-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_outputs_outputs_products_outputs_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
