# Generated by Django 5.0 on 2023-12-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
