# Generated by Django 5.0 on 2023-12-19 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_salary_absence_salary_advances_salary_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
