# Generated by Django 5.0 on 2024-02-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0011_alter_cart_barcode'),
        ('base', '0007_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
    ]
