# Generated by Django 5.0 on 2023-12-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_registry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra_Expense',
        ),
    ]
