# Generated by Django 5.0 on 2024-02-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_ad_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
