# Generated by Django 5.0 on 2023-12-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_medium_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
