# Generated by Django 5.0 on 2023-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_category_client_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=50),
        ),
    ]
