# Generated by Django 5.0 on 2023-12-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming_products',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='incoming_products',
            name='products',
        ),
        migrations.RemoveField(
            model_name='manualreciept',
            name='client',
        ),
        migrations.RemoveField(
            model_name='manualreciept',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='manualreciept',
            name='products',
        ),
        migrations.RemoveField(
            model_name='manualreciept_products',
            name='manualreciept',
        ),
        migrations.RemoveField(
            model_name='manualreciept_products',
            name='products',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='products',
        ),
        migrations.RemoveField(
            model_name='medium_products',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='medium_products',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outputs',
            name='client',
        ),
        migrations.RemoveField(
            model_name='outputs',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='outputs',
            name='products',
        ),
        migrations.RemoveField(
            model_name='outputs_products',
            name='output',
        ),
        migrations.RemoveField(
            model_name='outputs_products',
            name='products',
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
        migrations.DeleteModel(
            name='Incoming_Products',
        ),
        migrations.DeleteModel(
            name='ManualReciept',
        ),
        migrations.DeleteModel(
            name='ManualReciept_Products',
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
        migrations.DeleteModel(
            name='Medium_Products',
        ),
        migrations.DeleteModel(
            name='Outputs',
        ),
        migrations.DeleteModel(
            name='Outputs_Products',
        ),
    ]
