# Generated by Django 5.0 on 2023-12-12 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
