# Generated by Django 5.0 on 2024-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limit_less',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='limit_more',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
