# Generated by Django 5.0 on 2024-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_ad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
    ]
