# Generated by Django 5.0 on 2023-12-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_cart_product_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
