# Generated by Django 5.0 on 2023-12-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_medium_products_medium_medium_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField()),
                ('phonenumber', models.CharField(default='1212231243', max_length=30)),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField()),
                ('Reclaimed_products', models.FloatField()),
                ('previous_depts', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DelievaryArrived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('output_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.output')),
            ],
        ),
        migrations.CreateModel(
            name='Output_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField(default=0)),
                ('discount', models.FloatField()),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.output')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='products',
            field=models.ManyToManyField(through='base.Output_Products', to='base.product'),
        ),
    ]
