# Generated by Django 5.0 on 2023-12-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_codeverivecation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
