# Generated by Django 5.0 on 2023-12-12 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_cart_cart_products_cart_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_products',
            options={'ordering': ['products__added']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-added']},
        ),
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
