# Generated by Django 5.0 on 2024-02-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_chat_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
