# Generated by Django 5.0 on 2023-12-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_quantity_order_products_num_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_num',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='base.Order_Product', to='base.product'),
        ),
        migrations.DeleteModel(
            name='Order_Products',
        ),
    ]
