# Generated by Django 5.0 on 2023-12-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
