# Generated by Django 5.0 on 2023-12-20 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_incoming_incoming_product_incoming_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='barcode',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='manualreceipt',
            name='barcode',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='output',
            name='barcode',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200),
        ),
    ]
