# Generated by Django 5.0 on 2023-12-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_cart_products_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
