# Generated by Django 5.0 on 2023-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_products_num_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_num',
            field=models.IntegerField(default=0),
        ),
    ]
