# Generated by Django 5.0 on 2024-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_manualreceipt_recive_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt',
            name='verify_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
