# Generated by Django 5.0 on 2024-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_manualreceipt_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt',
            name='recive_payment',
            field=models.FloatField(default=0.0),
        ),
    ]
