# Generated by Django 5.0 on 2023-12-21 19:23

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_incoming_barcode_manualreceipt_barcode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Points',
        ),
        migrations.AddField(
            model_name='output',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
