# Generated by Django 4.2.10 on 2024-02-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0022_alter_product_product_type'),
        ('base', '0014_rename_notification_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='date',
        ),
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='employee',
        ),
        migrations.AlterField(
            model_name='returnedgoodssupplier',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReturnedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('goods', models.ManyToManyField(through='base.ReturnedGoodsSupplier', to='Clients_and_Products.product')),
            ],
        ),
        migrations.AddField(
            model_name='returnedgoodssupplier',
            name='returned_goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.returnedgoods'),
        ),
    ]
