# Generated by Django 5.0 on 2024-02-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0008_alter_manualreceipt_barcode_alter_output_barcode'),
        ('base', '0014_rename_notification_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenManualReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.manualreceipt')),
            ],
        ),
    ]
