# Generated by Django 5.0 on 2023-12-14 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('deliverd', models.BooleanField(default=False)),
                ('clinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('products', models.ManyToManyField(to='base.product')),
            ],
        ),
    ]
