# Generated by Django 5.0 on 2023-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_order_products_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
