# Generated by Django 5.0 on 2023-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_medium_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputs_products',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
