# Generated by Django 5.0 on 2024-01-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_manualreceipt_recive_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_on_salary',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extra_expense',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
