# Generated by Django 5.0 on 2023-12-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_point_points_output_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesemployee',
            name='representative',
        ),
        migrations.AlterField(
            model_name='employee',
            name='sale_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='SalesEmployee',
        ),
    ]
