# Generated by Django 4.2.10 on 2024-02-22 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_returnedgoodssupplier_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedgoodssupplier',
            name='returned_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.returnedgoods'),
        ),
    ]
