# Generated by Django 4.2.10 on 2024-02-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_returnedgoodssupplier_returned_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='returned_goods',
        ),
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='ReturnedGoods',
        ),
        migrations.DeleteModel(
            name='ReturnedGoodsSupplier',
        ),
    ]
