# Generated by Django 5.0 on 2024-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_advance_on_salary_reason_alter_bonus_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite',
            name='deposite_name',
            field=models.CharField(default='_', max_length=50),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='withdraw_name',
            field=models.CharField(default='_', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='detail_deposite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='details_withdraw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
