# Generated by Django 5.0 on 2023-12-22 08:08

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_salesemployee_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
