# Generated by Django 5.0 on 2023-12-13 01:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('سوبرماركت', 'سوبرماركت'), ('مقهى', 'مقهى'), ('محل جملة', 'محل جملة'), ('محل نصف جملة', 'محل نصف جملة')], default=' ', max_length=75),
        ),
        migrations.AddField(
            model_name='client',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213876543232', max_length=128, region='DZ'),
        ),
    ]
