# Generated by Django 5.0 on 2024-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_deposite_deposite_name_withdraw_withdraw_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='deposite_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_name',
            field=models.CharField(max_length=50),
        ),
    ]
