# Generated by Django 5.0 on 2023-12-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_client_category_client_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
