# Generated by Django 5.0 on 2023-12-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_incoming_incoming_product_incoming_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming_product',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='incoming_product',
            name='products',
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
        migrations.DeleteModel(
            name='Incoming_Product',
        ),
    ]
