# Generated by Django 5.0 on 2024-02-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_frozenmanualreceipts_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedSupplierPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.returnedgoodssupplier')),
            ],
        ),
    ]
