# Generated by Django 5.0 on 2023-12-22 08:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213672007698', max_length=128, region='DZ'),
        ),
    ]
