# Generated by Django 4.2.10 on 2024-02-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0022_alter_product_product_type'),
        ('base', '0017_remove_returnedgoodssupplier_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedGoodsSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('reason', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product')),
                ('returned_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.returnedgoods')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='returnedgoods',
            name='goods',
            field=models.ManyToManyField(through='base.ReturnedGoodsSupplier', to='Clients_and_Products.product'),
        ),
    ]
