# Generated by Django 5.0 on 2024-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_deposite_deposite_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt',
            name='recive_payment',
            field=models.FloatField(),
        ),
    ]
