# Generated by Django 5.0 on 2023-12-22 08:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_output_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
