# Generated by Django 5.0 on 2023-12-19 16:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_incoming_product_incoming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=30)),
                ('num_truck', models.IntegerField(null=True)),
                ('code_verefy', models.IntegerField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField()),
                ('Reclaimed_products', models.FloatField(default=0)),
                ('previous_depts', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incoming')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='incoming',
            name='products',
            field=models.ManyToManyField(through='base.Incoming_Product', to='base.product'),
        ),
    ]
