# Generated by Django 5.0 on 2023-12-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_product_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='phomnenumber',
        ),
    ]
