# Generated by Django 5.0 on 2024-02-22 21:09

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_returnedsupplierpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='returnedsupplierpackage',
            name='goods',
        ),
        migrations.AddField(
            model_name='returnedsupplierpackage',
            name='goods',
            field=models.ManyToManyField(to='base.returnedgoodssupplier'),
        ),
    ]
