# Generated by Django 4.2.10 on 2024-02-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_returnedgoods_returnedgoodssupplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('goods', models.ManyToManyField(to='base.returnedgoodsclient')),
            ],
        ),
    ]
