# Generated by Django 5.0 on 2023-12-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_customuser_location_delete_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
