# Generated by Django 5.0 on 2024-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_manualreceipt_recive_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreceipt',
            name='recive_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
