# Generated by Django 5.0 on 2023-12-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_incoming_incoming_product_incoming_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming_product',
            old_name='products',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='incoming_product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='incoming_product',
            name='quantity',
        ),
    ]
