# Generated by Django 4.2.10 on 2024-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_returnedclientpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedclientpackage',
            name='goods',
            field=models.ManyToManyField(blank=True, null=True, to='base.returnedgoodsclient'),
        ),
    ]
