# Generated by Django 5.0 on 2023-12-15 03:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breath_date', models.DateField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('type_employee', models.CharField(max_length=20)),
                ('number_track', models.IntegerField()),
                ('salery', models.FloatField()),
                ('sale_perce', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=30)),
                ('num_truck', models.IntegerField()),
                ('code_verefy', models.IntegerField()),
                ('recive_pyement', models.FloatField()),
                ('discount', models.FloatField()),
                ('previous_depts', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.IntegerField()),
                ('purch_price', models.FloatField()),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incoming')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='incoming',
            name='product',
            field=models.ManyToManyField(through='base.Incoming_Products', to='base.product'),
        ),
    ]
