# Generated by Django 5.0 on 2024-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_customuser_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='date',
        ),
        migrations.AddField(
            model_name='returnedsupplierpackage',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
