# Generated by Django 5.0 on 2023-12-19 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_products_incoming_product_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Medeom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0)),
                ('num_item', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('medeom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medeom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='medeom',
            name='products',
            field=models.ManyToManyField(through='base.Products_Medeom', to='base.product'),
        ),
    ]
