# Generated by Django 5.0 on 2024-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_manualreceipt_recive_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance_on_salary',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='detail_deposite',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extra_expense',
            name='reason',
            field=models.TextField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='code_verefy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='phonenumber',
            field=models.CharField(default='000 208 0660', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualreceipt',
            name='phonenumber',
            field=models.CharField(default='000 208 0660', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualreceipt',
            name='recive_payment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='output',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='output',
            name='phonenumber',
            field=models.CharField(default='000 208 0660', max_length=20),
        ),
        migrations.AlterField(
            model_name='output',
            name='verify_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnedgoodsclient',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnedgoodssupplier',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='details_withdraw',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
