# Generated by Django 4.2.10 on 2024-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_returnedclientpackage_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedclientpackage',
            name='goods',
            field=models.ManyToManyField(to='base.returnedgoodsclient'),
        ),
    ]
