# Generated by Django 4.2.10 on 2024-02-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_alter_salary_barcode'),
        ('base', '0021_alter_returnedclientpackage_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagedproduct',
            name='date',
        ),
        migrations.AddField(
            model_name='damagedproduct',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee'),
        ),
        migrations.CreateModel(
            name='ReturnedDamagedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('goods', models.ManyToManyField(to='base.damagedproduct')),
            ],
        ),
    ]
