# Generated by Django 5.0 on 2024-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_advance_on_salary_reason_alter_bonus_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
