# Generated by Django 5.0 on 2023-12-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_customuser_email_codeverivecation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='rabee@email.com', max_length=50, unique=True),
        ),
    ]
