# Generated by Django 5.0 on 2024-02-23 20:33

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_alter_salary_barcode'),
        ('base', '0022_remove_damagedproduct_date_damagedpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedpackage',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='damagedproduct',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee'),
        ),
        migrations.AddField(
            model_name='returnedclientpackage',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='returnedsupplierpackage',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, editable=False, max_length=200),
        ),
    ]
