# Generated by Django 5.0 on 2024-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_output_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_client',
            name='bank_name',
            field=models.CharField(blank=True, default='_', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='debt_supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='_', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, default='_', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='recieved_payment',
            name='bank_name',
            field=models.CharField(blank=True, default='_', max_length=60, null=True),
        ),
    ]
