# Generated by Django 4.2.10 on 2024-02-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Resources', '0002_alter_salary_barcode'),
        ('base', '0022_remove_damagedproduct_date_damagedproduct_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedproduct',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee'),
        ),
    ]
