# Generated by Django 5.0 on 2023-12-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_incoming_agent_alter_incoming_code_verefy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming_products',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='incoming_products',
            name='products',
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
        migrations.DeleteModel(
            name='Incoming_Products',
        ),
    ]
