# Generated by Django 5.0 on 2024-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_debt_client_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, default=' ', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sale_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
