# Generated by Django 5.0 on 2024-02-25 08:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_damagedpackage_barcode_damagedproduct_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='DZ'),
        ),
    ]
