# Generated by Django 5.0 on 2024-01-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_employee_notes_alter_employee_sale_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products_medium',
            options={'ordering': ['id']},
        ),
    ]
