# Generated by Django 5.0 on 2023-12-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_incoming_incoming_products_incoming_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming_products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
