# Generated by Django 5.0 on 2023-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_damagedproduct_returnedgoodsclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualreciept_products',
            name='manualreciept',
        ),
        migrations.RemoveField(
            model_name='manualreciept_products',
            name='products',
        ),
        migrations.AlterField(
            model_name='products_medium',
            name='num_item',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ManualReciept',
        ),
        migrations.DeleteModel(
            name='ManualReciept_Products',
        ),
    ]
