# Generated by Django 5.0 on 2024-01-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_products_medium_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreceipt',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manualreceipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
