# Generated by Django 5.0 on 2023-12-24 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverivecation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 3, 38, 27, 975375, tzinfo=datetime.timezone.utc)),
        ),
    ]
