# Generated by Django 5.0 on 2024-01-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_manualreceipt_discount_alter_incoming_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ['-date']},
        ),
    ]
