# Generated by Django 5.0 on 2024-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
