# Generated by Django 5.0 on 2023-12-24 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_codeverivecation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='created_at',
            field=models.DateTimeField(default='2022-3-3'),
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 3, 39, 51, 475373, tzinfo=datetime.timezone.utc)),
        ),
    ]
