# Generated by Django 5.0 on 2023-12-15 16:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_absence_award_discount_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
