# Generated by Django 5.0 on 2023-12-21 11:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_manualreciept_products_manualreciept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('recive_payment', models.FloatField()),
                ('discount', models.FloatField()),
                ('reclaimed_products', models.FloatField()),
                ('previous_depts', models.FloatField()),
                ('remaining_amount', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReceipt_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('num_item', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('manualreceipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.manualreceipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='manualreceipt',
            name='products',
            field=models.ManyToManyField(through='base.ManualReceipt_Products', to='base.product'),
        ),
    ]
