# Generated by Django 5.0 on 2024-01-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_incoming_options_alter_output_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming_product',
            options={'ordering': ['-product_id']},
        ),
        migrations.AlterModelOptions(
            name='manualreceipt_products',
            options={'ordering': ['-product_id']},
        ),
        migrations.AlterModelOptions(
            name='output_products',
            options={'ordering': ['-products_id']},
        ),
    ]
