# Generated by Django 5.0 on 2023-12-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_manualreceipt_manualreceipt_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
    ]
