# Generated by Django 5.0 on 2023-12-24 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_codeverivecation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 3, 40, 10, 658995, tzinfo=datetime.timezone.utc)),
        ),
    ]
