# Generated by Django 5.0 on 2024-02-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_customuser_store_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='store_category',
        ),
    ]
