# Generated by Django 5.0 on 2023-12-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_modelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelName',
        ),
    ]
