# Generated by Django 5.0 on 2024-01-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_total_output_products_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='details',
            field=models.TextField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
