# Generated by Django 5.0 on 2024-03-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0029_alter_client_notes'),
        ('Human_Resources', '0006_alter_absence_date_alter_advance_on_salary_date_and_more'),
        ('base', '0029_alter_chatmessage_options_alter_supplier_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedgoodsclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='returnedgoodsclient',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='returnedgoodssupplier',
            name='supplier',
        ),
        migrations.AddField(
            model_name='returnedclientpackage',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnedclientpackage',
            name='employee',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnedsupplierpackage',
            name='employee',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Human_Resources.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnedsupplierpackage',
            name='supplier',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='base.supplier'),
            preserve_default=False,
        ),
    ]
