# Generated by Django 5.0 on 2023-12-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_delete_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputs',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DelevaryArrived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('output_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.outputs')),
            ],
        ),
    ]
