# Generated by Django 5.0 on 2023-12-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='num_absence',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='amoumt_deducted',
            new_name='deduct',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='reason_discount',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='type_employee',
            new_name='job_position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='sale_perce',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salery',
            new_name='sale_percentage',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='number_track',
            new_name='truck_num',
        ),
        migrations.RenameField(
            model_name='overtime',
            old_name='deserved_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='info',
        ),
        migrations.CreateModel(
            name='Advance_On_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_award', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
