# Generated by Django 5.0 on 2023-12-24 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 18, 35, 41, 108162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 18, 45, 41, 108162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 18, 45, 41, 105162, tzinfo=datetime.timezone.utc)),
        ),
    ]
