# Generated by Django 4.2.8 on 2023-12-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_outputs_date_delevaryarrived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='breath_date',
            new_name='birth_date',
        ),
    ]
