# Generated by Django 5.0 on 2023-12-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_num_absence_absence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_expense',
            name='barcode',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='base.employee')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_employee_salaries', to='base.employee')),
            ],
        ),
    ]
