# Generated by Django 5.0 on 2024-01-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_expense_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id']},
        ),
    ]
