# Generated by Django 4.2.8 on 2023-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_breath_date_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number_track',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sale_perce',
            field=models.FloatField(null=True),
        ),
    ]
