# Generated by Django 5.0 on 2023-12-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_extra_expense_barcode_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('claim_name', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('مورد', 'مورد'), ('عميل', 'عميل')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bank', models.CharField(default='نقدا', max_length=60)),
                ('reciept_num', models.CharField(max_length=60)),
            ],
        ),
    ]
