# Generated by Django 5.0 on 2024-01-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_employee_options_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='damagedproduct',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='returnedgoodsclient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='returnedgoodssupplier',
            options={'ordering': ['-id']},
        ),
    ]
