# Generated by Django 5.0 on 2023-12-25 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_codeverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2023, 12, 25, 10, 10, 16, 396636, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='CodeVerivecation',
        ),
    ]
