# Generated by Django 5.0 on 2023-12-16 13:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_debt_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='truck_num',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ManualReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_code', models.IntegerField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ')),
                ('recive_pyement', models.FloatField()),
                ('Reclaimed_products', models.FloatField()),
                ('previous_debts', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManualReciept_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('manualreciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.manualreciept')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='manualreciept',
            name='products',
            field=models.ManyToManyField(through='base.ManualReciept_Products', to='base.product'),
        ),
    ]
