# Generated by Django 5.0 on 2024-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_category_options_alter_damagedproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='verify_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_per_carton',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_per_item',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
