# Generated by Django 5.0 on 2023-12-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_employee_notes_product_barcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='reason_award',
            new_name='reason',
        ),
    ]
