# Generated by Django 5.0 on 2023-12-25 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_codeverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2023, 12, 25, 12, 55, 16, 688943, tzinfo=datetime.timezone.utc)),
        ),
    ]
