# Generated by Django 5.0 on 2024-01-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients_and_Products', '0002_product_alter_cart_items_and_more'),
        ('Receipts', '0002_alter_incoming_products_and_more'),
        ('base', '0035_remove_absence_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedgoodssupplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='product_order_envoy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='mediumtwo_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='returnedgoodsclient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='products_medium',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='damagedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='products',
            field=models.ManyToManyField(through='base.Products_Medium', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='mediumtwo',
            name='products',
            field=models.ManyToManyField(through='base.MediumTwo_Products', to='Clients_and_Products.product'),
        ),
        migrations.AlterField(
            model_name='orderenvoy',
            name='products',
            field=models.ManyToManyField(through='base.Product_Order_Envoy', to='Clients_and_Products.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
