# Generated by Django 5.0 on 2024-03-12 11:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_returnedgoodssupplier_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ', unique=True),
        ),
    ]
