# Generated by Django 5.0 on 2023-12-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rename_reason_award_bonus_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='deduct',
            new_name='amount',
        ),
    ]
