# Generated by Django 4.2.8 on 2023-12-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_num_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phomnenumber',
            new_name='phonenumber',
        ),
    ]
