# Generated by Django 5.0 on 2023-12-26 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 0, 53, 47, 413322, tzinfo=datetime.timezone.utc)),
        ),
    ]
