# Generated by Django 5.0 on 2023-12-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_rename_deduct_absence_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='breath_date',
        ),
    ]
