# Generated by Django 5.0 on 2024-03-13 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 13, 8, 53, 2, 812588, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnedgoodsclient',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 13, 8, 53, 10, 566088, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnedgoodssupplier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 13, 8, 53, 17, 293819, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
