# Generated by Django 5.0 on 2023-12-26 03:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_codeverification_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 3, 13, 56, 805334, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
