# Generated by Django 5.0 on 2024-04-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_damagedproduct_date_returnedgoodsclient_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnedgoodsclient',
            options={'ordering': ['id']},
        ),
    ]
