# Generated by Django 4.2.8 on 2023-12-23 09:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_mediumtwo_alter_num_number_mediumtwo_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SY'),
        ),
    ]
