# Generated by Django 5.0 on 2024-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_returnedgoodsclient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='get_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
