# Generated by Django 5.0 on 2023-12-26 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_codeverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 3, 31, 53, 316328, tzinfo=datetime.timezone.utc)),
        ),
    ]
