# Generated by Django 5.0 on 2023-12-26 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_codeverification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 8, 1, 11, 81421, tzinfo=datetime.timezone.utc)),
        ),
    ]
