# Generated by Django 5.0 on 2024-05-09 13:55

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumtwo',
            name='barcode',
            field=models.CharField(default=base.models.generate_barcode, max_length=200),
        ),
    ]
