# Generated by Django 4.2.8 on 2023-12-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_num_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediumtwo_products',
            name='total_price',
        ),
    ]
