# Generated by Django 5.0 on 2024-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_mediumtwo_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('driver', 'driver'), ('employee', 'employee')], default='employee', max_length=30),
            preserve_default=False,
        ),
    ]
