# Generated by Django 5.0 on 2023-12-26 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_output_delivered_alter_codeverification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 9, 5, 31, 833007, tzinfo=datetime.timezone.utc)),
        ),
    ]
