# Generated by Django 4.2.8 on 2023-12-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_mediumtwo_products_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
