# Generated by Django 4.2.8 on 2023-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_rename_iamge_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumtwo_products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
