# Generated by Django 5.0 on 2023-12-26 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_codeverification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='delievaryarrived',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 19, 28, 15, 256518, tzinfo=datetime.timezone.utc)),
        ),
    ]
