# Generated by Django 5.0 on 2023-12-26 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_delievaryarrived_is_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 21, 22, 49, 90474, tzinfo=datetime.timezone.utc)),
        ),
    ]
