# Generated by Django 4.2.8 on 2023-12-23 15:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_mediumtwo_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='DZ'),
        ),
    ]
