# Generated by Django 5.0 on 2024-05-14 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='info',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
