# Generated by Django 5.0 on 2023-12-26 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_codeverification_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 21, 23, 58, 684697, tzinfo=datetime.timezone.utc)),
        ),
    ]
