# Generated by Django 4.2.8 on 2023-12-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Num',
        ),
        migrations.RemoveField(
            model_name='orderenvoy',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='orderenvoy',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
