# Generated by Django 5.0 on 2023-12-26 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_codeverification_expires_at_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 21, 52, 9, 687694, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
