# Generated by Django 4.2.8 on 2023-12-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_delete_num_remove_orderenvoy_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order_envoy',
            name='num_item',
        ),
        migrations.RemoveField(
            model_name='product_order_envoy',
            name='total_price',
        ),
    ]
