# Generated by Django 4.2.8 on 2023-12-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_product_order_envoy_num_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediumtwo_products',
            name='mediumtwo',
        ),
        migrations.RemoveField(
            model_name='mediumtwo_products',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderenvoy',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product_order_envoy',
            name='order_envoy',
        ),
        migrations.RemoveField(
            model_name='product_order_envoy',
            name='product',
        ),
        migrations.DeleteModel(
            name='MediumTwo',
        ),
        migrations.DeleteModel(
            name='MediumTwo_Products',
        ),
        migrations.DeleteModel(
            name='OrderEnvoy',
        ),
        migrations.DeleteModel(
            name='Product_Order_Envoy',
        ),
    ]
