# Generated by Django 5.0 on 2024-05-14 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_orderenvoy_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderenvoy',
            name='phonenumber',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{7}$')]),
        ),
    ]
