# Generated by Django 5.0 on 2024-05-15 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_orderenvoy_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='orderenvoy',
            name='phonenumber',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{8}$')]),
        ),
    ]
