# Generated by Django 5.0 on 2024-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_customuser_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='type',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='info_type',
            field=models.CharField(blank=True, choices=[('order', 'order'), ('info', 'info')], max_length=50, null=True),
        ),
    ]
