# Generated by Django 4.2.8 on 2023-12-24 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_codeverivecation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 10, 6, 12, 901773, tzinfo=datetime.timezone.utc)),
        ),
    ]
