# Generated by Django 5.0 on 2023-12-31 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_customuser_managers_orderenvoy_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_medium',
            old_name='discount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 2, 24, 19, 11425, tzinfo=datetime.timezone.utc)),
        ),
    ]
