# Generated by Django 5.0 on 2024-06-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_customuser_address_alter_customuser_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='info',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='info_type',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='details',
            field=models.JSONField(default={'id': 'no id'}),
        ),
    ]
