# Generated by Django 4.2.8 on 2023-12-24 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_codeverivecation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 10, 58, 7, 215899, tzinfo=datetime.timezone.utc)),
        ),
    ]
