# Generated by Django 5.0 on 2024-06-19 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rename_delievaryarrived_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(error_messages={'invalid': 'رقم الهاتف يجب أن يبدأ ب 05 , 06 أو 07 يتبعه 8 أرقام'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(05|06|07)\\d{8}$')]),
        ),
    ]
