# Generated by Django 4.2.8 on 2023-12-25 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_rename_clinet_order_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='phonenubmer',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 9, 4, 38, 910569, tzinfo=datetime.timezone.utc)),
        ),
    ]
