# Generated by Django 5.0 on 2024-06-19 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_delivery_options_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يبدأ ب 05 , 06 أو 07 يتبعه 8 أرقام', regex='^(05|06|07)\\d{8}$')]),
        ),
    ]
