# Generated by Django 4.2.8 on 2023-12-25 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_rename_phonenubmer_supplier_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtime',
            old_name='deserved_amount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 23, 53, 10, 653850, tzinfo=datetime.timezone.utc)),
        ),
    ]
