# Generated by Django 4.2.8 on 2023-12-25 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_rename_deserved_amount_overtime_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='amoumt_deducted',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='num_absence',
            new_name='days',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 23, 59, 23, 175834, tzinfo=datetime.timezone.utc)),
        ),
    ]
