# Generated by Django 4.2.8 on 2023-12-25 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_bonus_alter_codeverivecation_expires_at_delete_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='reason_discount',
            new_name='reason',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 0, 7, 55, 133620, tzinfo=datetime.timezone.utc)),
        ),
    ]
