# Generated by Django 4.2.8 on 2023-12-26 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_rename_total_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance_On_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('barcode', models.CharField(default=' ', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='extraexpense',
            name='employee',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 8, 57, 54, 902067, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Advance',
        ),
        migrations.DeleteModel(
            name='ExtraExpense',
        ),
    ]
