# Generated by Django 4.2.8 on 2023-12-26 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_remove_withdraw_name_user_withdraw_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(default='_', max_length=60)),
                ('receipt_num', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='Debt_Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('نقدا', 'نقدا'), ('بنك', 'بنك')], max_length=30)),
                ('bank_name', models.CharField(default='_', max_length=60)),
                ('check_num', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('receipt_num', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='deptsclients',
            name='client',
        ),
        migrations.RemoveField(
            model_name='deptssuppliers',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Expence',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 9, 19, 32, 125594, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DeptsClients',
        ),
        migrations.DeleteModel(
            name='DeptsSuppliers',
        ),
    ]
