# Generated by Django 4.2.8 on 2023-12-26 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_debt_client_debt_supplier_expense_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Points',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 10, 8, 36, 365222, tzinfo=datetime.timezone.utc)),
        ),
    ]
