# Generated by Django 4.2.8 on 2023-12-26 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_rename_point_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 12, 20, 58, 663754, tzinfo=datetime.timezone.utc)),
        ),
    ]
