# Generated by Django 4.2.8 on 2023-12-26 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_customuser_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverivecation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 17, 30, 1, 244862, tzinfo=datetime.timezone.utc)),
        ),
    ]
