# Generated by Django 4.2.8 on 2023-12-26 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_codeverivecation_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 17, 47, 56, 336594, tzinfo=datetime.timezone.utc)),
        ),
    ]
