# Generated by Django 4.2.8 on 2023-12-27 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_codeverivecation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='delevaryarrived',
            name='is_delivered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 23, 39, 770307, tzinfo=datetime.timezone.utc)),
        ),
    ]
