# Generated by Django 4.2.8 on 2023-12-27 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_delevaryarrived_is_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 25, 15, 809300, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='delevaryarrived',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
