# Generated by Django 4.2.8 on 2023-12-27 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_codeverivecation_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 14, 35, 10, 123109, tzinfo=datetime.timezone.utc)),
        ),
    ]
