# Generated by Django 4.2.8 on 2023-12-27 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_alter_codeverivecation_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 20, 33, 26, 998462, tzinfo=datetime.timezone.utc)),
        ),
    ]
