# Generated by Django 4.2.8 on 2023-12-27 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_codeverivecation_expires_at_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesemployee',
            name='representative',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 22, 9, 57, 932932, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='SalesEmployee',
        ),
    ]
