# Generated by Django 4.2.8 on 2023-12-31 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_rename_discount_products_medium_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 10, 28, 33, 271028, tzinfo=datetime.timezone.utc)),
        ),
    ]
