# Generated by Django 4.2.8 on 2024-01-06 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_rename_sale_price_products_medium_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='num_truck',
        ),
        migrations.AlterField(
            model_name='codeverivecation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 4, 59, 898023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='Reclaimed_products',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='code_verefy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='previous_depts',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='recive_pyement',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
