# Generated by Django 4.2.8 on 2024-01-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_remove_customuser_is_verified_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='products',
        ),
        migrations.RemoveField(
            model_name='incoming',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='incoming_product',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='incoming_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manualreceipt',
            name='client',
        ),
        migrations.RemoveField(
            model_name='manualreceipt',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='manualreceipt',
            name='products',
        ),
        migrations.RemoveField(
            model_name='manualreceipt_products',
            name='manualreceipt',
        ),
        migrations.RemoveField(
            model_name='manualreceipt_products',
            name='product',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='client',
        ),
        migrations.DeleteModel(
            name='Deposite',
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
        migrations.DeleteModel(
            name='Incoming_Product',
        ),
        migrations.DeleteModel(
            name='ManualReceipt',
        ),
        migrations.DeleteModel(
            name='ManualReceipt_Products',
        ),
        migrations.DeleteModel(
            name='WithDraw',
        ),
    ]
