# Generated by Django 4.2.8 on 2024-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_remove_incoming_employee_remove_incoming_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='debts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
